require 'rbconfig'

module Gem
  module Micro
    class BinWrapperEmitter
      def initialize(name)
        @name = name
      end
      
      # Returns the full path to where the bin wrapper script should be created.
      def bin_wrapper_file
        File.join(rbconfig('bindir'), @name)
      end
      
      # Creates the bin wrapper script in bin_wrapper_file.
      def create_bin_wrapper!
        File.open(bin_wrapper_file, 'w') { |f| f << to_ruby }
        File.chmod(755, bin_wrapper_file)
      end
      
      # Returns a string representation of the bin wrapper file.
      def to_ruby
%{#!#{ File.join(rbconfig('bindir'), rbconfig('ruby_install_name')) }
#
# This file was generated by MicroGem (µgem).
#
# The application '#{@name}' is installed as part of a gem, and
# this file is here to facilitate running it.

require 'rubygems'

version = "> 0"
if ARGV.first =~ /^_(.*)_$/ and Gem::Version.correct? $1 then
  version = $1
  ARGV.shift
end

gem '#{@name}', version
load '#{@name}'
}
      end
      
      private
      
      def rbconfig(key)
        ::Config::CONFIG[key]
      end
    end
  end
end